version: '3.8'

services:
  app:
    build:
      context: .
    
    # networks:
    #   - flaskapp_net
    container_name: my-app
    expose:
      - 5000
    
    volumes:
      - .:/app/

# networks:
#   default:
#     name: net
#     external: true

# networks:
#   net:
#     driver: macvlan
#     # enable_ipv6: true                   # if needed
#     driver_opts:
#       parent: ens33
#     ipam:
#       config:
#         - subnet: 192.168.0.0/24
#           gateway: 192.168.0.1
#           ip_range: 192.168.0.8/30
