version: '3.8'

services:
  app:
    build:
      context: .
    container_name: my-app
    expose:
      - 5000
    
    volumes:
      - .:/app/

networks:
  default:
    name: dev
    external: true
